---
driver_plugin: vagrant
driver_config:
  require_chef_omnibus: true

platforms:
- name: ubuntu-14.04
  run_list:
  - recipe[apt]
- name: ubuntu-12.04
  run_list:
  - recipe[apt]
- name: ubuntu-10.04
  run_list:
  - recipe[apt]
- name: debian-7.6
- name: centos-6.4

suites:
- name: stock_system_and_user
  run_list:
  - recipe[user::data_bag]
  - recipe[rvm::system]
  - recipe[rvm::user]
  attributes:
    users:
    - wigglebottom
    rvm:
      user_installs:
      - user: wigglebottom
        default_ruby: 1.9.3-p484
- name: rubies
  run_list:
  - recipe[java]
  - recipe[rvm::system]
  attributes:
    rvm:
      default_ruby: system
      rubies:
      - 1.9.3
      - version: 1.9.3-p327
        patch: railsexpress
      - version: 1.8.7
        rubygems_version: 1.6.0
      - jruby
      - ree
- name: rbx
  run_list:
  - recipe[rvm::system]
  attributes:
    rvm:
      default_ruby: rbx
- name: installs
  run_list:
  - recipe[user::data_bag]
  - recipe[rvm::user_install]
  attributes:
    users:
    - virgil1
    - virgil2
    rvm:
      installs:
        virgil1:
          installer_flags: --version 1.19.6
        virgil2:
          installer_flags: --version 1.21.20
